fragment HeroParts on Hero {
  __typename
  title
  subtitle
  phone
  serviceAreas
  cta {
    __typename
    text
    phone
  }
}

fragment ServicesParts on Services {
  __typename
  title
  description
  icon
  features {
    __typename
    feature
  }
}

fragment TestimonialsParts on Testimonials {
  __typename
  name
  location
  body
  rating
}

fragment AboutParts on About {
  __typename
  title
  content
  stats {
    __typename
    number
    label
  }
}

fragment BlogParts on Blog {
  __typename
  title
  date
  excerpt
  featuredImage
  body
}

fragment ContactParts on Contact {
  __typename
  title
  subtitle
  phone
  email
  address
  city
  ctaTitle
  ctaSubtitle
  rating
}

fragment FooterParts on Footer {
  __typename
  companyName
  tagline
  description
  phone
  email
  address
  city
  serviceAreas
  ownerInfo
  services {
    __typename
    service
  }
  credentials {
    __typename
    credential
  }
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  siteDescription
  primaryPhone
  primaryEmail
  businessAddress
  businessCity
  logoPath
}
